version: "3.9"

services:
  ocr:
    build: .
    container_name: ocr-server
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - MODEL_ID=/app/model
      - STORAGE_PATH=/data
    volumes:
      - ${STORAGE}:/data
      - ${MODEL_DIR}:/app/model
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

    runtime: nvidia
